name: summarization
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - amply=0.1.5
  - arrow=1.2.3
  - arrow-cpp=11.0.0
  - async-timeout=4.0.2
  - attrs=22.2.0
  - aws-c-auth=0.6.24
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.11
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.18
  - aws-c-http=0.7.4
  - aws-c-io=0.13.17
  - aws-c-mqtt=0.8.6
  - aws-c-s3=0.2.4
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.19.7
  - aws-sdk-cpp=1.10.57
  - binaryornot=0.4.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - chardet=5.1.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - coin-or-cbc=2.10.8
  - coin-or-cgl=0.60.6
  - coin-or-clp=1.17.7
  - coin-or-osi=0.108.7
  - coin-or-utils=2.11.6
  - coincbc=2.10.8
  - colorama=0.4.6
  - cookiecutter=2.1.1
  - cryptography=39.0.1
  - dataclasses=0.8
  - datasets=2.10.1
  - dill=0.3.6
  - docutils=0.19
  - evaluate=0.2.2
  - filelock=3.9.0
  - frozenlist=1.3.3
  - fsspec=2023.1.0
  - gensim=4.3.0
  - gflags=2.2.2
  - glog=0.6.0
  - huggingface_hub=0.12.1
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - jinja2=3.1.2
  - jinja2-time=0.2.0
  - joblib=1.2.0
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libabseil=20220623.0
  - libarrow=11.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=7.88.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgoogle-cloud=2.7.0
  - libgrpc=1.51.1
  - libhwloc=2.9.0
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libprotobuf=3.21.12
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libthrift=0.18.0
  - libutf8proc=2.8.0
  - libuuid=2.32.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lxml=4.9.2
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - mkl=2022.2.1
  - multidict=6.0.4
  - multiprocess=0.70.14
  - ncurses=6.3
  - ninja=1.11.1
  - nltk=3.8.1
  - numpy=1.24.2
  - openssl=3.0.8
  - orc=1.8.2
  - packaging=23.0
  - pandas=1.5.3
  - parquet-cpp=1.5.1
  - pip=23.0.1
  - platformdirs=3.0.0
  - pooch=1.7.0
  - pulp=2.7.0
  - py-rouge=1.1
  - pyarrow=11.0.0
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-slugify=8.0.1
  - python-xxhash=3.2.0
  - python_abi=3.10
  - pytorch=1.12.1
  - pytz=2022.7.1
  - pyyaml=6.0
  - re2=2023.02.01
  - readline=8.1.2
  - regex=2022.10.31
  - requests=2.28.2
  - responses=0.18.0
  - s2n=1.3.37
  - sacremoses=0.0.53
  - scikit-learn=1.2.1
  - scipy=1.10.1
  - setuptools=67.4.0
  - six=1.16.0
  - sleef=3.5.1
  - smart_open=6.3.0
  - snappy=1.1.9
  - tbb=2021.8.0
  - text-unidecode=1.3
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tokenizers=0.13.2
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unidecode=1.3.6
  - urllib3=1.26.14
  - wheel=0.38.4
  - xxhash=0.8.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.2
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - blis==0.7.9
      - catalogue==2.0.8
      - confection==0.0.4
      - cymem==2.0.7
      - en-core-web-md==3.4.1
      - en-core-web-sm==3.4.1
      - en-coreference-web-trf==3.4.0a2
      - langcodes==3.3.0
      - murmurhash==1.0.9
      - pathy==0.10.1
      - preshed==3.0.8
      - pydantic==1.10.5
      - spacy==3.4.4
      - spacy-alignments==0.9.0
      - spacy-experimental==0.6.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - spacy-transformers==1.1.9
      - srsly==2.4.6
      - thinc==8.1.8
      - transformers==4.25.1
      - typer==0.7.0
      - wasabi==0.10.1
